/*!
 * Jodit Editor (https://xdsoft.net/jodit/)
 * Released under MIT see LICENSE.txt in the project root for license information.
 * Copyright (c) 2013-2021 Valeriy Chupurnov. All rights reserved. https://xdsoft.net
 */

module.exports = {
	'Type something': '輸入一些內容',
	'Advanced': '進階',
	'About Jodit': '關於Jodit',
	'Jodit Editor': 'Jodit Editor',
	"Jodit User's Guide": '開發者指南',
	'contains detailed help for using': '使用說明',
	'For information about the license, please go to our website:': '有關授權的資訊，請訪問我們的網站：',
	'Buy full version': '購買完整版本',
	'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.': 'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.',
	'Anchor': '錨點',
	'Open in new tab': '在新視窗開啟',
	'Open editor in fullsize': '全螢幕編輯',
	'Clear Formatting': '清除格式',
	'Fill color or set the text color': '顏色',
	'Redo': '重做',
	'Undo': '取消',
	'Bold': '粗體',
	'Italic': '斜體',
	'Insert Unordered List': '符號列表',
	'Insert Ordered List': '編號',
	'Align Center': '居中',
	'Align Justify': '左右對齊',
	'Align Left': '靠左',
	'Align Right': '靠右',
	'Insert Horizontal Line': '分隔線',
	'Insert Image': '圖片',
	'Insert file': '文件',
	'Insert youtube/vimeo video': 'youtube/vimeo 影片',
	'Insert link': '超連結',
	'Font size': '字型大小',
	'Font family': '字型',
	'Insert format block': '插入格式化文字',
	'Normal': '本文',
	'Heading 1': '標題1',
	'Heading 2': '標題2',
	'Heading 3': '標題3',
	'Heading 4': '標題4',
	'Quote': '引用',
	'Code': '代碼',
	'Insert': '插入',
	'Insert table': '表格',
	'Decrease Indent': '減少縮排',
	'Increase Indent': '增加縮排',
	'Select Special Character': '選擇特殊符號',
	'Insert Special Character': '特殊符號',
	'Paint format': '格式複製',
	'Change mode': '改變模式',
	'Margins': '外邊距（Margins）',
	'top': '上',
	'right': '右',
	'bottom': '下',
	'left': '左',
	'Styles': '樣式',
	'Classes': 'Classes',
	'Align': '對齊方式',
	'Right': '靠右',
	'Center': '置中',
	'Left': '靠左',
	'--Not Set--': '無',
	'Src': '來源網址',
	'Title': '標題',
	'Alternative': '替代文字',
	'Link': '超連結',
	'Open link in new tab': '在新視窗開啟連結',
	'Image': '圖片',
	'file': '檔案',
	'Advansed': '進階',
	'Image properties': '圖片屬性',
	'Cancel': '取消',
	'Ok': '確定',
	'Your code is similar to HTML. Keep as HTML?': '你貼上的文字是一段html代碼，是否保留原始格式',
	'Paste as HTML': '貼上html代碼',
	'Keep': '保留原始格式',
	'Clean': '符合目標格式',
	'Insert as Text': '把html代碼視為一般文字',
	'Word Paste Detected': '貼上Word格式內容',
	'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?': '正在貼上 Word/Excel 的內容，是否保留原始格式？',
	'Insert only Text': '只保留純文字',
	'File Browser': '檔案管理',
	'Error on load list': '載入list錯誤',
	'Error on load folders': '載入folders錯誤',
	'Are you sure?': '你確定嗎？',
	'Enter Directory name': '輸入路徑',
	'Create directory': '創建路徑',
	'type name': '輸入名稱',
	'Drop image': '拖拉圖片到此',
	'Drop file': '拖拉檔案到此',
	'or click': '或點擊',
	'Alternative text': '替代文字',
	'Browse': '瀏覽',
	'Upload': '上傳',
	'Background': '背景色',
	'Text': '文字',
	'Top': '頂部',
	'Middle': '中間',
	'Bottom': '底部',
	'Insert column before': '在左側插入直欄',
	'Insert column after': '在右側插入直欄',
	'Insert row above': '在上方插入橫列',
	'Insert row below': '在下方插入橫列',
	'Delete table': '刪除表格',
	'Delete row': '刪除橫列',
	'Delete column': '刪除直欄',
	'Empty cell': '清除內容',
	'Chars: %d': '字符數: %d',
	'Words: %d': '單詞數: %d',
	'Strike through': '刪除線',
	'Underline': '下劃線',
	'superscript': '上標',
	'subscript': '下標',
	'Cut selection': '剪切',
	'Select all': '全選',
	'Break': '中斷',
	'Search for': '查找',
	'Replace with': '替換為',
	'Replace': '替換',
	'Paste': '貼上',
	'Choose Content to Paste': '選擇內容並貼上',
	'All': '全部',
	'source': '原始碼',
	'bold': '粗體',
	'italic': '斜體',
	'brush': '筆刷',
	'link': '超連結',
	'undo': '還原',
	'redo': '重做',
	'table': '表格',
	'image': '圖片',
	'eraser': '橡皮擦',
	'paragraph': '段落',
	'fontsize': '字體大小',
	'video': '影片',
	'font': '字型',
	'about': '關於',
	'print': '列印',
	'symbol': '符號',
	'underline': '底線',
	'strikethrough': '刪除線',
	'indent': '增加縮排',
	'outdent': '減少縮排',
	'fullsize': '全螢幕',
	'shrink': '縮小',
	'copyformat': '複製格式',
	'hr': '水平分割線',
	'ul': '符號清單',
	'ol': '數字清單',
	'cut': '剪下',
	'selectall': '全選',
	'Open link': '打開鏈接',
	'Edit link': '編輯鏈接',
	'No follow': '不追蹤',
	'Unlink': '取消連結',
	'Eye': '查看',
	' URL': 'URL',
	'Reset': '重置',
	'Save': '保存',
	'Save as ...': '保存為',
	'Resize': '調整大小',
	'Crop': '剪裁',
	'Width': '寬',
	'Height': '高',
	'Keep Aspect Ratio': '保留長寬比例',
	'Yes': '是',
	'No': '不',
	'Remove': '移除',
	'Select': '選擇',
	'Select %s': '選擇: %s',
	'Update': '更新',
	'Vertical align': '垂直對齊',
	'Merge': '合併',
	'Add column': '添加直欄',
	'Add row': '添加橫列',
	'Border': '邊框',
	'Embed code': '嵌入代碼',
	'Delete': '刪除',
	'Horizontal align': '水平對齊',
	'Filter': '篩選',
	'Sort by changed': '依修改時間排序',
	'Sort by name': '依名稱排序',
	'Sort by size': '依大小排序',
	'Add folder': '新建文件夾',
	'Split': '分割',
	'Split vertical': '垂直分割',
	'Split horizontal': '水平分割',
	'You can only edit your own images. Download this image on the host?': '你只能編輯你自己的圖片。是否下載此圖片到本地?',
	'The image has been successfully uploaded to the host!': '圖片上傳成功',
	'palette': '調色盤',
	'pencil': '鉛筆',
	'There are no files': '此目錄中沒有檔案。',
	'Rename': '重新命名',
	'Enter new name': '輸入新名稱',
	'preview': '預覽',
	'download': '下載',
	'Paste from clipboard': '從剪貼簿貼上',
	"Your browser doesn't support direct access to the clipboard.": '瀏覽器無法存取剪貼簿。',
	'Copy selection': '複製已選取內容',
	'copy': '複製',
	'Border radius': '邊框圓角',
	'Show all': '顯示全部',
	'Apply': '套用',
	'Please fill out this field': '請填寫此欄位',
	'Please enter a web address': '請輸入網址',
	'Default': '預設',
	'Circle': '圓圈',
	'Dot': '圓點',
	'Quadrate': '方格',
	'Find': '搜尋',
	'Find Previous': '往前搜尋',
	'Find Next': '往後搜尋',
	'Insert className': '插入class名稱'
};
